library('tidyverse')
library(RCurl)
library(readr)
library(nlme)

# function to import and clean data from Github
# removes wheelchair athletes to get homogeneous times
get_mar_data <- function(race_year){
  mar_file = getURL(paste0("https://raw.githubusercontent.com/llimllib/bostonmarathon/master/results/",race_year,"/results.csv"))
  return(read.csv(text = mar_file) %>%
     mutate(year = race_year, official = as.numeric(official))
     filter(!stringr::str_detect(bib,'W'), !is.na(official)) %>%
     select(name, city, gender, age, official, state, country))
}

# loop through each year to build dataset
baa <- get_mar_data(2001)
for(mar_year in 2002:2014){
  baa <- rbind(baa, get_mar_data(mar_year))
  print(mar_year)
}

# import CSVs for data and ref tables for qualification times and weather
# baa <- read_csv("Documents/baa_2001_2014.csv")
# BAA_qualifying_times <- read_csv("Documents/BAA_qualifying_times.csv")
# BAA_marathon_weather <- read_csv("Documents/BAA_marathon_weather.csv")

# bring in weather for each year, qualifying standards by age and gender
# mark any run where time >30 minutes over qualifying time (gender-adjusted for that year's average time)
comps <- baa %>% mutate(match_var = 1) %>% 
  full_join(BAA_qualifying_times %>% mutate(match_var = 1), by = 'match_var') %>%
  filter(gender == Gender & age >= Min_age & age <= Max_age & year >= Min_year & year <= Max_year) %>%
  mutate(official = as.numeric(official)) %>%
  select(-c(match_var, Min_age, Max_age, Gender, Min_year, Max_year)) %>%
  inner_join(BAA_marathon_weather, by = c('year'='Year')) %>%
  group_by(gender) %>%
  mutate(avg_gender = mean(official, na.rm = T)) %>%
  group_by(gender, year) %>% 
  mutate(avg_gender_yr = mean(official, na.rm = T)) %>%
  ungroup() %>%
  filter(!is.na(official)) %>%
  mutate(adj_official = official * (avg_gender/avg_gender_yr)) %>%
  mutate(non_comp = if_else(adj_official - Time > 30, 1, 0))

# check for missing values, overall structure of dataset  
sapply(comps, function(x) sum(is.na(x)))
str(comps)

# drop people with fewer than 5 races, 
#                  more than two runs with time >30 min over qualifying time
#                  no consecutive runs
bos_mar <- comps %>% 
  group_by(name, city, gender, country) %>% 
  mutate(count = n(), sum_non_comp = sum(non_comp)) %>%
  ungroup() %>%
  filter(count > 5, sum_non_comp < 2) %>% 
  arrange(name, age, year, city, gender, state, country) %>% 
  mutate(repeated = ifelse(lead(name) == name & 
                  lead(gender) == gender & 
                  lead(state) == state &
                  lead(country) == country &
                  lead(age) == age+1 &
                  lead(year) == year + 1, 1, 0)) %>%
  group_by(name, city, gender, country) %>%
  mutate(has_repeat = ifelse(sum(repeated) >=1, 1, 0)) %>% 
  filter(has_repeat == 1) %>%
  select(-c(count, repeated, Time, has_repeat, avg_gender, avg_gender_yr, adj_official, non_comp, sum_non_comp))

# add ID variable for plotting and modelling
bos_ID <- bos_mar %>% 
  select(name, city, gender, country) %>% 
  distinct() %>% 
  rowid_to_column(.,'ID') %>%
  inner_join(bos_mar, by = c('name','city','gender','country'))

hist(bos_ID$year, xlab = 'Year', ylab = '', col = 'dodgerblue', main = '(Repeating) runners per year')

# assess times by age + gender, split by year
ggplot(bos_ID, aes(age, official, col = gender, group = ID)) + 
  geom_point(alpha = .20) + 
  geom_smooth(method = 'lm', se = F, alpha = .15) + 
  geom_smooth(data = bos_ID, aes(age, official, group = gender)) +
  facet_wrap(~year)
